version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: trip-planner-postgres
    environment:
      POSTGRES_DB: tripplanner
      POSTGRES_USER: tripplanner
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trip-planner-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trip-planner-backend
    environment:
      - DB_USERNAME=tripplanner
      - DB_PASSWORD=password
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - trip-planner-network
    volumes:
      - ./backend:/app
      - backend_cache:/root/.m2

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trip-planner-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080/ws
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - trip-planner-network
    volumes:
      - ./frontend:/app
      - frontend_cache:/app/node_modules

volumes:
  postgres_data:
  backend_cache:
  frontend_cache:

networks:
  trip-planner-network:
    driver: bridge