spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tripplanner
    username: ${DB_USERNAME:tripplanner}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    jwt:
      secret: ${JWT_SECRET:your-secret-key-change-this-in-production}
      expiration: 86400000 # 24 hours in milliseconds

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.tripplanner: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# Custom application properties
app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001
  file:
    upload-dir: uploads/
    max-file-size: 10MB

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method